### ISSUE TITLE
web service?

### ISSUE THREAD

**Issue by ghost** [gelisam/cabal-rangefinder#26]
hpack-convert offers a simple REST interface from a hosted server... consider doing the same? This seems like a tool that many would be willing to try from a browser on their hackage package or a github repo, before committing to download and use it more.

**Comment by gelisam** [comment]
That sounds weird to me, I don't understand why hpack-convert would do that. Clearly their users already have a Haskell environment, so installing the tool should be trivial. What is the gain? Is it simply faster to run it via the web service because you don't have to compile hpack and its dependencies first?

If that's the case, then doing the same for cabal-rangefinder would not make sense, because compiling your project with every possible version of its dependencies takes a lot longer than compiling cabal-rangefinder and its dependencies once.

Another reason why it makes less sense for cabal-rangefinder to do it is that cabal-rangefinder needs access to your source in order to compile it, it's not a pure source-to-source transformation like hpack-convert. So it would be more like a continuous-integration service.

Third, compiling all those versions takes a lot of CPU time, more than a continuous-integration system would, so I'm worried about the server costs. I do have a 5$/mo instance idling around though, and the Haskell community isn't that big, so maybe I should do some cost analysis before deciding that it would be too expensive.

**Comment by ghost** [comment]
For me personally, I didn't have time to install and figure pack-deps at work, but I did have a few minutes to browse the website (similar web vs local). I also often hesitate to disturb my local dev environment, so if I only have stack installed, I drag my feet on installing GHC and cabal globally.

I also often do not want to freeze up my machine, while I am doing other work or need to compile other projects.

What would also be awesome would be if this project could detect when it needs to rerun (in local mode or ci server mode), where it has a local DB file recording the most recent set of dependencies, and if a new dependency has been added.

I would limit the service to one or two concurrent users at a time (maybe save results, with a publicly visible history). If you actually hit problems with cost and load, that would be a great sign that people are adopting it.

**Comment by gelisam** [comment]
> What would also be awesome would be if this project could detect when it needs to rerun (in local mode or ci server mode), where it has a local DB file recording the most recent set of dependencies, and if a new dependency has been added.

That's too optimistic: even if you don't change your dependencies, other changes to the code could have an effect on which definitions from those dependencies you are using or with which types you are using them, which might only work with the latest version.

**Comment by ghost** [comment]
I am closing for now as I would not use the service at this time. I might be interested again at a later time.
